### ISSUE TITLE
updated version will not run or install

### ISSUE THREAD

**Issue by romxuk** [ArthurMoore85/pi_romulus#21]
I tried to use the newest version with updates and it will not run. I tried removing the files and re adding them and got errors I also get errors trying to run it

running it gives the below output

pi@retropie:~/pi_romulus $ python romulus.py
Traceback (most recent call last):
  File "romulus.py", line 9, in <module>
    from forms import SearchForm
  File "/home/pi/pi_romulus/forms/__init__.py", line 8, in <module>
    from forms.search import SearchForm
  File "/home/pi/pi_romulus/forms/search.py", line 12, in <module>
    from api.providers import EmuApi
  File "/home/pi/pi_romulus/api/providers/__init__.py", line 12, in <module>
    from .emuapi import EmuApi
  File "/home/pi/pi_romulus/api/providers/emuapi.py", line 17, in <module>
    from api.base import Api
  File "/home/pi/pi_romulus/api/base.py", line 24, in <module>
    from io_utils.compression import Compression
  File "/home/pi/pi_romulus/io_utils/compression.py", line 12, in <module>
    import py7zlib
ImportError: No module named py7zlib

and installing gives this
pi@retropie:~/pi_romulus $ sudo pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by ArthurMoore85** [comment]
Having just tested the latest code in a sandbox environment, it did seem to work fine for me. The error you get indicates that new packages were not updated.
Could you try the following:

1. Run 'git pull' to get latest changes (I made some this morning unrelated to the bug)
2. Run 'pip install -r requirements'. This step is the likely cause of your errors as it installs new 3rd party packages.

After this you should be able to run the app.

**Comment by romxuk** [comment]
pi@retropie:~/pi_romulus $ git pull
Already up-to-date.

**Comment by romxuk** [comment]
I think I have found a fix for the issue

apt-get remove python-pip

easy_install pip

then 

sudo pip install -r requirements.txt

this allows the installation and makes it run ok

**Comment by romxuk** [comment]
one other issue though, some roms do not relocate right, the NDS game i tested just now went into roms folder not roms/nds

**Comment by ArthurMoore85** [comment]
Good to hear that you found the culprit, I did suspect it was a pip issue.
In regards to the NDS addition, DS is not supported in the app at the moment, so the reason it is ending up in the roms folder is because it does not know where to be saved. I have added DS support on my tasklist. You can track its progress here: https://gitlab.com/arthurmoore85/pi_romulus/issues/23

**Comment by romxuk** [comment]
I have just added the support into the files and all working right now
apart from I would prefer it not uncompress the files but all good now
thanks for your help

**Comment by ArthurMoore85** [comment]
All supported ROMs (I will add a list of supported ROMs on the page later) are checked if compressed files are supported by their emulators. If the emulator supports compressed files, Romulus will not decompress them, only if they are not supported if compressed. The original idea behind this app was for RetroPie, so keeping compressed files if they are not supported was not useful to the user. This option will be available in version 2 however.

Since the original issue appears resolved, I am going to close this ticket. Should you have further issues, or feel that the ticket is not resolved, feel free to open a ticket again.
